### ISSUE TITLE
No need for the call/1 wrapper

### ISSUE THREAD

**Issue by pmoura** [fnogatz/plammar#1]
Ih the following line, the `call/1` wrapper is not required and comes with a small performance cost:

https://github.com/fnogatz/plammar/blob/c62ed0a8c17c59fe81047546ea584cb364e77ed5/prolog/plammar/format_space.pl#L167

Found by the Logtalk linter.

**Comment by fnogatz** [comment]
Hi Paulo, thank you for reporting this! I changed it accordingly.
