### ISSUE TITLE
Expensive call to =../2

### ISSUE THREAD

**Issue by pmoura** [fnogatz/plammar#2]
The `=../2` built-in predicate is computationally expensive. In the following line, it can be replaced by a call to the `functor/3` built-in predicate:

https://github.com/fnogatz/plammar/blob/c62ed0a8c17c59fe81047546ea584cb364e77ed5/prolog/plammar/pt_ast.pl#L586

Reported by the Logtalk linter as:

```text
*     Suspicious call: A=..[B|C] instead of functor(A,B,D)
*       while compiling object 'plammar/pt_ast'
*       in file /Users/pmoura/Downloads/plammar-master/prolog/plammar/pt_ast.pl between lines 583-598
```

**Comment by fnogatz** [comment]
Thank you for reporting this, Paulo. Just out of curiosity: this was not the only occurrence that the Logtalk linter reported, was it? There are some other places in plammar's source code where this bad pattern was used.

**Comment by pmoura** [comment]
Possibly. A lot happened in the last 20 days since the original report 🙂 I suggest you try the Logtalk linter in the latest version of your code. Use the latest Logtalk version preferably as it includes linter improvements. See https://logtalk.org/using_tools_with_prolog.html

**Comment by fnogatz** [comment]
Okay, running the Logtalk linter now and will work through its reportings.
