### ISSUE TITLE
use_module/1 directives can be simplified

### ISSUE THREAD

**Issue by pmoura** [fnogatz/plammar#3]
The following directives:

https://github.com/fnogatz/plammar/blob/c62ed0a8c17c59fe81047546ea584cb364e77ed5/prolog/plammar/pt_ast.pl#L5-L8

can be simplified to:

```logtalk
:- use_module(util).
:- use_module(state).
:- use_module(format_space).
:- use_module(format_check).
```

It will also improve loading times. Same for other occurrences of this directive in other files.

**Comment by fnogatz** [comment]
Thank you again, Paulo. This has been changed now.
